# Generated by Django 6.1 on 2026-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
