# Generated by Django 6.1 on 2026-08-18 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='accounts.bloodbankprofile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
